<?php

declare(strict_types=1);

namespace Kodano\MobileCoupon\Test\Unit\Plugin\DataProvider;

use Kodano\MobileCoupon\Plugin\DataProvider\RuleDataProviderPlugin;
use Magento\Framework\Data\Collection\AbstractDb;
use Magento\SalesRule\Model\Rule;
use Magento\SalesRule\Model\Rule\DataProvider;
use Magento\SalesRule\Model\Coupon;
use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;

/**
 * Unit tests for RuleDataProviderPlugin
 *
 * Tests the addition of 'on_mobile' field to rule data.
 */
class RuleDataProviderPluginTest extends TestCase
{
    private RuleDataProviderPlugin $plugin;
    private DataProvider|MockObject $dataProvider;
    private AbstractDb|MockObject $collection;

    protected function setUp(): void
    {
        $this->dataProvider = $this->createMock(DataProvider::class);
        $this->collection = $this->getMockBuilder(AbstractDb::class)
            ->disableOriginalConstructor()
            ->onlyMethods(['getItemById'])
            ->getMockForAbstractClass();

        $this->plugin = new RuleDataProviderPlugin();
    }

    /**
     * Create a mock Rule object
     *
     * @return Rule|MockObject
     */
    private function createRuleMock(): Rule|MockObject
    {
        return $this->getMockBuilder(Rule::class)
            ->disableOriginalConstructor()
            ->onlyMethods(['getId', 'getPrimaryCoupon'])
            ->addMethods(['getCouponType', 'getUseAutoGeneration'])
            ->getMock();
    }

    /**
     * Test that on_mobile field is added for specific coupon
     */
    public function testAddsOnMobileFieldForSpecificCoupon(): void
    {
        $ruleId = 1;
        $result = [
            $ruleId => [
                'rule_id' => $ruleId,
                'name' => 'Test Rule',
            ]
        ];

        $primaryCoupon = $this->createMock(Coupon::class);
        $primaryCoupon->expects($this->once())
            ->method('getId')
            ->willReturn(10);
        $primaryCoupon->expects($this->once())
            ->method('getData')
            ->with('on_mobile')
            ->willReturn(1);

        $rule = $this->createRuleMock();
        $rule->expects($this->once())
            ->method('getId')
            ->willReturn($ruleId);
        $rule->expects($this->once())
            ->method('getCouponType')
            ->willReturn(Rule::COUPON_TYPE_SPECIFIC);
        $rule->expects($this->once())
            ->method('getUseAutoGeneration')
            ->willReturn(false);
        $rule->expects($this->once())
            ->method('getPrimaryCoupon')
            ->willReturn($primaryCoupon);

        $this->collection->expects($this->once())
            ->method('getItemById')
            ->with($ruleId)
            ->willReturn($rule);

        $this->dataProvider->expects($this->once())
            ->method('getCollection')
            ->willReturn($this->collection);

        $result = $this->plugin->afterGetData($this->dataProvider, $result);

        $this->assertArrayHasKey('on_mobile', $result[$ruleId]);
        $this->assertSame(1, $result[$ruleId]['on_mobile']);
    }

    /**
     * Test that on_mobile field is not added for auto-generated coupons
     */
    public function testSkipsAutoGeneratedCoupons(): void
    {
        $ruleId = 1;
        $result = [
            $ruleId => [
                'rule_id' => $ruleId,
                'name' => 'Test Rule',
            ]
        ];

        $rule = $this->createRuleMock();
        $rule->expects($this->once())
            ->method('getId')
            ->willReturn($ruleId);
        $rule->expects($this->once())
            ->method('getCouponType')
            ->willReturn(Rule::COUPON_TYPE_SPECIFIC);
        $rule->expects($this->once())
            ->method('getUseAutoGeneration')
            ->willReturn(true);
        $rule->expects($this->never())
            ->method('getPrimaryCoupon');

        $this->collection->expects($this->once())
            ->method('getItemById')
            ->with($ruleId)
            ->willReturn($rule);

        $this->dataProvider->expects($this->once())
            ->method('getCollection')
            ->willReturn($this->collection);

        $result = $this->plugin->afterGetData($this->dataProvider, $result);

        $this->assertArrayNotHasKey('on_mobile', $result[$ruleId]);
    }

    /**
     * Test that on_mobile field is not added for non-specific coupon types
     */
    public function testSkipsNonSpecificCouponTypes(): void
    {
        $ruleId = 1;
        $result = [
            $ruleId => [
                'rule_id' => $ruleId,
                'name' => 'Test Rule',
            ]
        ];

        $rule = $this->createRuleMock();
        $rule->expects($this->once())
            ->method('getId')
            ->willReturn($ruleId);
        $rule->expects($this->once())
            ->method('getCouponType')
            ->willReturn(Rule::COUPON_TYPE_NO_COUPON);
        $rule->expects($this->never())
            ->method('getUseAutoGeneration');
        $rule->expects($this->never())
            ->method('getPrimaryCoupon');

        $this->collection->expects($this->once())
            ->method('getItemById')
            ->with($ruleId)
            ->willReturn($rule);

        $this->dataProvider->expects($this->once())
            ->method('getCollection')
            ->willReturn($this->collection);

        $result = $this->plugin->afterGetData($this->dataProvider, $result);

        $this->assertArrayNotHasKey('on_mobile', $result[$ruleId]);
    }

    /**
     * Test that null result is returned unchanged
     */
    public function testReturnsNullWhenResultIsNull(): void
    {
        $result = $this->plugin->afterGetData($this->dataProvider, null);

        $this->assertNull($result);
    }

    /**
     * Test that empty array result is returned unchanged
     */
    public function testReturnsEmptyArrayWhenResultIsEmpty(): void
    {
        $result = [];

        $result = $this->plugin->afterGetData($this->dataProvider, $result);

        $this->assertSame([], $result);
    }

    /**
     * Test that rule without primary coupon is skipped
     */
    public function testSkipsRuleWithoutPrimaryCoupon(): void
    {
        $ruleId = 1;
        $result = [
            $ruleId => [
                'rule_id' => $ruleId,
                'name' => 'Test Rule',
            ]
        ];

        $rule = $this->createRuleMock();
        $rule->expects($this->once())
            ->method('getId')
            ->willReturn($ruleId);
        $rule->expects($this->once())
            ->method('getCouponType')
            ->willReturn(Rule::COUPON_TYPE_SPECIFIC);
        $rule->expects($this->once())
            ->method('getUseAutoGeneration')
            ->willReturn(false);
        $rule->expects($this->once())
            ->method('getPrimaryCoupon')
            ->willReturn(null);

        $this->collection->expects($this->once())
            ->method('getItemById')
            ->with($ruleId)
            ->willReturn($rule);

        $this->dataProvider->expects($this->once())
            ->method('getCollection')
            ->willReturn($this->collection);

        $result = $this->plugin->afterGetData($this->dataProvider, $result);

        $this->assertArrayNotHasKey('on_mobile', $result[$ruleId]);
    }

    /**
     * Test that rule without ID is skipped
     */
    public function testSkipsRuleWithoutId(): void
    {
        $ruleId = 1;
        $result = [
            $ruleId => [
                'rule_id' => $ruleId,
                'name' => 'Test Rule',
            ]
        ];

        $rule = $this->createRuleMock();
        $rule->expects($this->once())
            ->method('getId')
            ->willReturn(null);
        $rule->expects($this->never())
            ->method('getCouponType');

        $this->collection->expects($this->once())
            ->method('getItemById')
            ->with($ruleId)
            ->willReturn($rule);

        $this->dataProvider->expects($this->once())
            ->method('getCollection')
            ->willReturn($this->collection);

        $result = $this->plugin->afterGetData($this->dataProvider, $result);

        $this->assertArrayNotHasKey('on_mobile', $result[$ruleId]);
    }

    /**
     * Test that multiple rules are processed correctly
     */
    public function testProcessesMultipleRules(): void
    {
        $ruleId1 = 1;
        $ruleId2 = 2;
        $result = [
            $ruleId1 => [
                'rule_id' => $ruleId1,
                'name' => 'Test Rule 1',
            ],
            $ruleId2 => [
                'rule_id' => $ruleId2,
                'name' => 'Test Rule 2',
            ]
        ];

        // First rule with mobile coupon
        $primaryCoupon1 = $this->createMock(Coupon::class);
        $primaryCoupon1->expects($this->once())
            ->method('getId')
            ->willReturn(10);
        $primaryCoupon1->expects($this->once())
            ->method('getData')
            ->with('on_mobile')
            ->willReturn(1);

        $rule1 = $this->createRuleMock();
        $rule1->expects($this->once())
            ->method('getId')
            ->willReturn($ruleId1);
        $rule1->expects($this->once())
            ->method('getCouponType')
            ->willReturn(Rule::COUPON_TYPE_SPECIFIC);
        $rule1->expects($this->once())
            ->method('getUseAutoGeneration')
            ->willReturn(false);
        $rule1->expects($this->once())
            ->method('getPrimaryCoupon')
            ->willReturn($primaryCoupon1);

        // Second rule with regular coupon
        $primaryCoupon2 = $this->createMock(Coupon::class);
        $primaryCoupon2->expects($this->once())
            ->method('getId')
            ->willReturn(20);
        $primaryCoupon2->expects($this->once())
            ->method('getData')
            ->with('on_mobile')
            ->willReturn(0);

        $rule2 = $this->createRuleMock();
        $rule2->expects($this->once())
            ->method('getId')
            ->willReturn($ruleId2);
        $rule2->expects($this->once())
            ->method('getCouponType')
            ->willReturn(Rule::COUPON_TYPE_SPECIFIC);
        $rule2->expects($this->once())
            ->method('getUseAutoGeneration')
            ->willReturn(false);
        $rule2->expects($this->once())
            ->method('getPrimaryCoupon')
            ->willReturn($primaryCoupon2);

        $this->collection->expects($this->exactly(2))
            ->method('getItemById')
            ->willReturnCallback(function ($id) use ($rule1, $rule2, $ruleId1, $ruleId2) {
                return match ($id) {
                    $ruleId1 => $rule1,
                    $ruleId2 => $rule2,
                    default => null,
                };
            });

        $this->dataProvider->expects($this->exactly(2))
            ->method('getCollection')
            ->willReturn($this->collection);

        $result = $this->plugin->afterGetData($this->dataProvider, $result);

        $this->assertArrayHasKey('on_mobile', $result[$ruleId1]);
        $this->assertSame(1, $result[$ruleId1]['on_mobile']);
        $this->assertArrayHasKey('on_mobile', $result[$ruleId2]);
        $this->assertSame(0, $result[$ruleId2]['on_mobile']);
    }
}

